### ISSUE TITLE
Pruning breaks Pippin?

### ISSUE THREAD

**Issue by qwahzi** [appditto/pippin_nano_wallet#27]
I believe Pippin has issues with pruned nodes, leading to semi-frequent 500s. Sometimes deleting/resetting PippinData helps, but not always:
```
for x in $(curl --silent -d '{ "action": "pending", "account": "nano_" }' 127.0.0.1:11338 | jq -r '.blocks|values[]'); do curl -d '{"action": "receive", "wallet": "wallet_", "account": "nano_", "block": "'"$x"'"}' 127.0.0.1:11338; done
{"error":"Block not found"}{"error":"Block not found"}{"error":"Block not found"}{"error":"Block not found"}500 Internal Server Error Server got itself in trouble
```

From pippin_wallet.log:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib64/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib64/python3.6/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib64/python3.6/site-packages/aiohttp/web_middlewares.py", line 108, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/pippin/server/pippin_server.py", line 79, in gateway
    return await self.receive(request, request_json)
  File "/usr/local/lib/python3.6/site-packages/pippin/server/pippin_server.py", line 283, in receive
    response = await wallet.receive(request_json['block'], work=work)
  File "/usr/local/lib/python3.6/site-packages/pippin/util/wallet.py", line 110, in receive
    block = await self._receive_block_create(hash, work)
  File "/usr/local/lib/python3.6/site-packages/pippin/util/wallet.py", line 79, in _receive_block_create
    balance = block_info['amount'] if not is_open else str(int(account_info['balance']) + int(block_info['amount']))
KeyError: 'amount'
```

One workaround is using the regular 7076 Nano node RPC to receive transactions first, and then going back to Pippin

**Comment by bbedward** [comment]
I'm rebuilding pippin in golang, let's explore this after that
