### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype (https://boompow.banano.cc/graphql)

### ISSUE THREAD

**Issue by PrideIsLife** [appditto/pippin_nano_wallet#29]
Hi,

This error occured since the switch to BPOW v2.
It happens occasionnaly when sending a transaction.

```
ERROR:aiohttp.server:work_generate task raised Exception
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/pippin/network/work_client.py", line 100, in work_generate
    result = task.result()
  File "/root/.local/lib/python3.9/site-packages/aiographql/client/client.py", line 274, in query
    return await self._http_request(
  File "/root/.local/lib/python3.9/site-packages/aiographql/client/client.py", line 207, in _http_request
    body = await resp.json()
  File "/root/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://boompow.banano.cc/graphql')
```

**Comment by bbedward** [comment]
This might be a case when BoomPow is unavailable or times out, but I'm going to close this since the Python version of pippin is no longer maintained. The GO version will be released soon
